name: "Epic: Investigation"
description: "Propose an investigation to explore a technical or product question."
title: "[Investigation]: "
labels: ["Epic: Investigation", "Meta: Unknown Priority"]
projects: ["inno-swp-2025/5"]
type: "Epic"
body:
  - type: textarea
    id: question-to-investigate
    attributes:
      label: "<h2> The Question </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text in this input field after the comment.
      value: |
        <!--
        Clearly state the primary question or hypothesis to be investigated.

        Example:

        Can we use a new, more efficient video encoding format (like AV1) to reduce data usage and improve startup time for users on slow networks, without significantly increasing server-side processing costs?
        -->
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "<h2> Context & Rationale </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text in this input field after the comment.
      value: |
        <!--
        Why is this investigation necessary? What problem does it address, what risk does it mitigate, or what opportunity does it explore? Link to relevant issues or documents.

        Example:

        Users in emerging markets with poor connectivity report long video load times (see #123). This leads to high drop-off rates in the first minute of app usage. AV1 is a promising technology, but we need to understand the trade-offs in terms of device compatibility, battery consumption, and our own CDN costs before committing to a full implementation.
        -->
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: "<h2> Proposed Approach </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text in this input field after the comment.
      value: |
        <!--
        Outline the high-level steps or tasks to be performed during this investigation. This is not a detailed implementation plan but a guide for the research.

        Example:

        1. Research AV1 hardware/software decoder support across our top 15 user devices.
        2. Build a proof-of-concept (POC) that encodes a sample set of 100 videos in both H.264 and AV1.
        3. Benchmark client-side performance (CPU, battery, load time) on 3 representative test devices (low, mid, high-end).
        4. Analyze server-side encoding time and cost implications.
        -->
    validations:
      required: false

  - type: textarea
    id: deliverables
    attributes:
      label: "<h2> Deliverables & Success Criteria </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text in this input field after the comment.
      value: |
        <!--
        What will be produced at the end of this investigation? How will we know it's complete and successful?

        Example:

        - [ ] A recommendation document summarizing the pros and cons of adopting AV1.
        - [ ] Benchmark data and a link to the POC repository.
        - [ ] A go/no-go decision for a follow-up User Story to implement AV1 encoding.
        -->
    validations:
      required: true

  - type: textarea
    id: sub-issues
    attributes:
      label: "<h2> Sub-issues </h2>"
      description: |
        Don't modify the default text in this input field.
      value: |
        Sub-issues are type `Backlog` issues that must be resolved to resolve this issue.
    validations:
      required: false
